/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  collection?: "design" | "websites" | "tools";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  collection?: "design" | "websites" | "tools";
  title?: string;
  authorDetails?: {
    profileImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    handle?: string;
    profileUrl?: string;
  };
  author?: AuthorReference;
  categories?: Array<string>;
  media?: {
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    width?: number;
    height?: number;
    videoUrl?: string;
  };
  sourcePlatform?: "Instagram" | "X" | "LinkedIn" | "Other";
  sourceUrl?: string;
  externalPostId?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  handle?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  profileUrl?: string;
  platform?: "Instagram" | "X" | "LinkedIn" | "Other";
  externalId?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Category
  | Slug
  | SanityImageAssetReference
  | AuthorReference
  | SanityFileAssetReference
  | GalleryItem
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../brasa-app/features/gallery/sanity-query.ts
// Variable: GALLERY_QUERY
// Query: {  "cursorExists": $cursor == null || count(*[    _type == "galleryItem" && _id == $cursor && collection == $collection &&    ($category == null || $category in categories)  ]) > 0,  "items": *[    _type == "galleryItem" && collection in ["design", "websites", "tools"] &&    ($collection == null || collection == $collection) &&    ($category == null || $category in categories) &&    ($id == null || _id == $id) && ($cursor == null || _id > $cursor)  ] | order(_id asc)[0...49] {    _id, title, collection, categories, sourcePlatform, sourceUrl, externalPostId,    "author": coalesce(authorDetails, author->{handle, profileUrl, profileImage}) {      handle, profileUrl, profileImage    },    media {type, width, height, "videoUrl": coalesce(video.asset->url, videoUrl), image, "dimensions": image.asset->metadata.dimensions}  }}
export type GALLERY_QUERY_RESULT = {
  cursorExists: boolean;
  items: Array<{
    _id: string;
    title: string | null;
    collection: "design" | "tools" | "websites" | null;
    categories: Array<string> | null;
    sourcePlatform: "Instagram" | "LinkedIn" | "Other" | "X" | null;
    sourceUrl: string | null;
    externalPostId: string | null;
    author: {
      handle: string | null;
      profileUrl: string | null;
      profileImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    media: {
      type: "image" | "video" | null;
      width: number | null;
      height: number | null;
      videoUrl: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "cursorExists": $cursor == null || count(*[\n    _type == "galleryItem" && _id == $cursor && collection == $collection &&\n    ($category == null || $category in categories)\n  ]) > 0,\n  "items": *[\n    _type == "galleryItem" && collection in ["design", "websites", "tools"] &&\n    ($collection == null || collection == $collection) &&\n    ($category == null || $category in categories) &&\n    ($id == null || _id == $id) && ($cursor == null || _id > $cursor)\n  ] | order(_id asc)[0...49] {\n    _id, title, collection, categories, sourcePlatform, sourceUrl, externalPostId,\n    "author": coalesce(authorDetails, author->{handle, profileUrl, profileImage}) {\n      handle, profileUrl, profileImage\n    },\n    media {type, width, height, "videoUrl": coalesce(video.asset->url, videoUrl), image, "dimensions": image.asset->metadata.dimensions}\n  }\n}': GALLERY_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
